#include"dao_SDL_Test.h"

DaoVmSpace *__daoVmSpace = NULL;
extern char** DaoStringList_ToStaticCStringArray( DaoList *slist );
#ifdef __cplusplus
extern "C"{
#endif
static void dao__CommonCreateState( DaoProcess *_proc, DaoValue *_p[], int _n );
static void dao__CommonArg( DaoProcess *_proc, DaoValue *_p[], int _n );
static void dao__CommonUsage( DaoProcess *_proc, DaoValue *_p[], int _n );
static void dao__CommonInit( DaoProcess *_proc, DaoValue *_p[], int _n );
static void dao__CommonEvent( DaoProcess *_proc, DaoValue *_p[], int _n );
static void dao__CommonQuit( DaoProcess *_proc, DaoValue *_p[], int _n );
static DaoFuncItem dao__Funcs[] = 
{
  { dao__CommonCreateState, "CommonCreateState( argv:list<string>, flags :int )=>CommonState" },
  { dao__CommonArg, "CommonArg( state :CommonState, index :int )=>int" },
  { dao__CommonUsage, "CommonUsage( state :CommonState )=>string" },
  { dao__CommonInit, "CommonInit( state :CommonState )=>int" },
  { dao__CommonEvent, "CommonEvent( state :CommonState, event :SDL_Event, done :int )=>int" },
  { dao__CommonQuit, "CommonQuit( state :CommonState )" },
  { NULL, NULL }
};
/* ../test/common.h */
static void dao__CommonCreateState( DaoProcess *_proc, DaoValue *_p[], int _n )
{
  static char **__argv = NULL;
  char **argv = __argv ? __argv : (__argv = DaoStringList_ToStaticCStringArray( (DaoList*)_p[0] ));
  unsigned int flags = (unsigned int) DaoValue_TryGetInteger( _p[1] );

  CommonState* _CommonCreateState = CommonCreateState( argv, flags );
  DaoProcess_WrapCdata( _proc, (void*) _CommonCreateState, dao_type_CommonState );
}
/* ../test/common.h */
static void dao__CommonArg( DaoProcess *_proc, DaoValue *_p[], int _n )
{
  CommonState* state = (CommonState*) DaoValue_TryCastCdata( _p[0], dao_type_CommonState );
  int index = (int) DaoValue_TryGetInteger( _p[1] );

  int _CommonArg = CommonArg( state, index );
  DaoProcess_PutInteger( _proc, (daoint) _CommonArg );
}
/* ../test/common.h */
static void dao__CommonUsage( DaoProcess *_proc, DaoValue *_p[], int _n )
{
  CommonState* state = (CommonState*) DaoValue_TryCastCdata( _p[0], dao_type_CommonState );

  const char* _CommonUsage = CommonUsage( state );
  DaoProcess_PutMBString( _proc, (char*) _CommonUsage );
}
/* ../test/common.h */
static void dao__CommonInit( DaoProcess *_proc, DaoValue *_p[], int _n )
{
  CommonState* state = (CommonState*) DaoValue_TryCastCdata( _p[0], dao_type_CommonState );

  SDL_bool _CommonInit = CommonInit( state );
  DaoProcess_PutInteger( _proc, (daoint) _CommonInit );
}
/* ../test/common.h */
static void dao__CommonEvent( DaoProcess *_proc, DaoValue *_p[], int _n )
{
  CommonState* state = (CommonState*) DaoValue_TryCastCdata( _p[0], dao_type_CommonState );
  SDL_Event* event = (SDL_Event*) DaoValue_TryCastCdata( _p[1], dao_type_SDL_Event );
  int done = (int) DaoValue_TryGetInteger( _p[2] );

  CommonEvent( state, event, &done );
  DaoProcess_PutInteger( _proc, (daoint) done );
}
/* ../test/common.h */
static void dao__CommonQuit( DaoProcess *_proc, DaoValue *_p[], int _n )
{
  CommonState* state = (CommonState*) DaoValue_TryCastCdata( _p[0], dao_type_CommonState );

  CommonQuit( state );
}
#ifdef __cplusplus
}
#endif
static DaoNumItem dao__Nums[] = 
{
  {  "AUDIO_F32LSB", DAO_DOUBLE, AUDIO_F32LSB},
  {  "AUDIO_F32MSB", DAO_DOUBLE, AUDIO_F32MSB},
  {  "AUDIO_S16LSB", DAO_DOUBLE, AUDIO_S16LSB},
  {  "AUDIO_S16MSB", DAO_DOUBLE, AUDIO_S16MSB},
  {  "AUDIO_S32LSB", DAO_DOUBLE, AUDIO_S32LSB},
  {  "AUDIO_S32MSB", DAO_DOUBLE, AUDIO_S32MSB},
  {  "AUDIO_S8", DAO_DOUBLE, AUDIO_S8},
  {  "AUDIO_U16LSB", DAO_DOUBLE, AUDIO_U16LSB},
  {  "AUDIO_U16MSB", DAO_DOUBLE, AUDIO_U16MSB},
  {  "AUDIO_U8", DAO_DOUBLE, AUDIO_U8},
  {  "BUFSIZ", DAO_DOUBLE, BUFSIZ},
  {  "BUS_ADRALN", DAO_DOUBLE, BUS_ADRALN},
  {  "BUS_ADRERR", DAO_DOUBLE, BUS_ADRERR},
  {  "BUS_NOOP", DAO_DOUBLE, BUS_NOOP},
  {  "BUS_OBJERR", DAO_DOUBLE, BUS_OBJERR},
  {  "CLD_CONTINUED", DAO_DOUBLE, CLD_CONTINUED},
  {  "CLD_DUMPED", DAO_DOUBLE, CLD_DUMPED},
  {  "CLD_EXITED", DAO_DOUBLE, CLD_EXITED},
  {  "CLD_KILLED", DAO_DOUBLE, CLD_KILLED},
  {  "CLD_NOOP", DAO_DOUBLE, CLD_NOOP},
  {  "CLD_STOPPED", DAO_DOUBLE, CLD_STOPPED},
  {  "CLD_TRAPPED", DAO_DOUBLE, CLD_TRAPPED},
  {  "DEFAULT_WINDOW_HEIGHT", DAO_DOUBLE, DEFAULT_WINDOW_HEIGHT},
  {  "DEFAULT_WINDOW_WIDTH", DAO_DOUBLE, DEFAULT_WINDOW_WIDTH},
  {  "DOMAIN", DAO_DOUBLE, DOMAIN},
  {  "EXIT_FAILURE", DAO_DOUBLE, EXIT_FAILURE},
  {  "EXIT_SUCCESS", DAO_DOUBLE, EXIT_SUCCESS},
  {  "FILENAME_MAX", DAO_DOUBLE, FILENAME_MAX},
  {  "FOPEN_MAX", DAO_DOUBLE, FOPEN_MAX},
  {  "FPE_FLTDIV", DAO_DOUBLE, FPE_FLTDIV},
  {  "FPE_FLTINV", DAO_DOUBLE, FPE_FLTINV},
  {  "FPE_FLTOVF", DAO_DOUBLE, FPE_FLTOVF},
  {  "FPE_FLTRES", DAO_DOUBLE, FPE_FLTRES},
  {  "FPE_FLTSUB", DAO_DOUBLE, FPE_FLTSUB},
  {  "FPE_FLTUND", DAO_DOUBLE, FPE_FLTUND},
  {  "FPE_INTDIV", DAO_DOUBLE, FPE_INTDIV},
  {  "FPE_INTOVF", DAO_DOUBLE, FPE_INTOVF},
  {  "FPE_NOOP", DAO_DOUBLE, FPE_NOOP},
  {  "FP_CHOP", DAO_DOUBLE, FP_CHOP},
  {  "FP_PREC_24B", DAO_DOUBLE, FP_PREC_24B},
  {  "FP_PREC_53B", DAO_DOUBLE, FP_PREC_53B},
  {  "FP_PREC_64B", DAO_DOUBLE, FP_PREC_64B},
  {  "FP_RND_DOWN", DAO_DOUBLE, FP_RND_DOWN},
  {  "FP_RND_NEAR", DAO_DOUBLE, FP_RND_NEAR},
  {  "FP_RND_UP", DAO_DOUBLE, FP_RND_UP},
  {  "FP_STATE_BYTES", DAO_DOUBLE, FP_STATE_BYTES},
  {  "HAVE_ABS", DAO_DOUBLE, HAVE_ABS},
  {  "HAVE_ALLOCA", DAO_DOUBLE, HAVE_ALLOCA},
  {  "HAVE_ALLOCA_H", DAO_DOUBLE, HAVE_ALLOCA_H},
  {  "HAVE_ATAN", DAO_DOUBLE, HAVE_ATAN},
  {  "HAVE_ATAN2", DAO_DOUBLE, HAVE_ATAN2},
  {  "HAVE_ATOF", DAO_DOUBLE, HAVE_ATOF},
  {  "HAVE_ATOI", DAO_DOUBLE, HAVE_ATOI},
  {  "HAVE_BCOPY", DAO_DOUBLE, HAVE_BCOPY},
  {  "HAVE_CALLOC", DAO_DOUBLE, HAVE_CALLOC},
  {  "HAVE_CEIL", DAO_DOUBLE, HAVE_CEIL},
  {  "HAVE_COPYSIGN", DAO_DOUBLE, HAVE_COPYSIGN},
  {  "HAVE_COS", DAO_DOUBLE, HAVE_COS},
  {  "HAVE_COSF", DAO_DOUBLE, HAVE_COSF},
  {  "HAVE_CTYPE_H", DAO_DOUBLE, HAVE_CTYPE_H},
  {  "HAVE_FABS", DAO_DOUBLE, HAVE_FABS},
  {  "HAVE_FLOOR", DAO_DOUBLE, HAVE_FLOOR},
  {  "HAVE_FREE", DAO_DOUBLE, HAVE_FREE},
  {  "HAVE_GETENV", DAO_DOUBLE, HAVE_GETENV},
  {  "HAVE_ICONV", DAO_DOUBLE, HAVE_ICONV},
  {  "HAVE_ICONV_H", DAO_DOUBLE, HAVE_ICONV_H},
  {  "HAVE_INTTYPES_H", DAO_DOUBLE, HAVE_INTTYPES_H},
  {  "HAVE_LIBC", DAO_DOUBLE, HAVE_LIBC},
  {  "HAVE_LOG", DAO_DOUBLE, HAVE_LOG},
  {  "HAVE_MALLOC", DAO_DOUBLE, HAVE_MALLOC},
  {  "HAVE_MATH_H", DAO_DOUBLE, HAVE_MATH_H},
  {  "HAVE_MEMCMP", DAO_DOUBLE, HAVE_MEMCMP},
  {  "HAVE_MEMCPY", DAO_DOUBLE, HAVE_MEMCPY},
  {  "HAVE_MEMMOVE", DAO_DOUBLE, HAVE_MEMMOVE},
  {  "HAVE_MEMORY_H", DAO_DOUBLE, HAVE_MEMORY_H},
  {  "HAVE_MEMSET", DAO_DOUBLE, HAVE_MEMSET},
  {  "HAVE_MPROTECT", DAO_DOUBLE, HAVE_MPROTECT},
  {  "HAVE_NANOSLEEP", DAO_DOUBLE, HAVE_NANOSLEEP},
  {  "HAVE_POW", DAO_DOUBLE, HAVE_POW},
  {  "HAVE_PUTENV", DAO_DOUBLE, HAVE_PUTENV},
  {  "HAVE_QSORT", DAO_DOUBLE, HAVE_QSORT},
  {  "HAVE_REALLOC", DAO_DOUBLE, HAVE_REALLOC},
  {  "HAVE_SA_SIGACTION", DAO_DOUBLE, HAVE_SA_SIGACTION},
  {  "HAVE_SCALBN", DAO_DOUBLE, HAVE_SCALBN},
  {  "HAVE_SETENV", DAO_DOUBLE, HAVE_SETENV},
  {  "HAVE_SETJMP", DAO_DOUBLE, HAVE_SETJMP},
  {  "HAVE_SIGACTION", DAO_DOUBLE, HAVE_SIGACTION},
  {  "HAVE_SIGNAL_H", DAO_DOUBLE, HAVE_SIGNAL_H},
  {  "HAVE_SIN", DAO_DOUBLE, HAVE_SIN},
  {  "HAVE_SINF", DAO_DOUBLE, HAVE_SINF},
  {  "HAVE_SNPRINTF", DAO_DOUBLE, HAVE_SNPRINTF},
  {  "HAVE_SQRT", DAO_DOUBLE, HAVE_SQRT},
  {  "HAVE_SSCANF", DAO_DOUBLE, HAVE_SSCANF},
  {  "HAVE_STDARG_H", DAO_DOUBLE, HAVE_STDARG_H},
  {  "HAVE_STDINT_H", DAO_DOUBLE, HAVE_STDINT_H},
  {  "HAVE_STDIO_H", DAO_DOUBLE, HAVE_STDIO_H},
  {  "HAVE_STDLIB_H", DAO_DOUBLE, HAVE_STDLIB_H},
  {  "HAVE_STRCASECMP", DAO_DOUBLE, HAVE_STRCASECMP},
  {  "HAVE_STRCHR", DAO_DOUBLE, HAVE_STRCHR},
  {  "HAVE_STRCMP", DAO_DOUBLE, HAVE_STRCMP},
  {  "HAVE_STRDUP", DAO_DOUBLE, HAVE_STRDUP},
  {  "HAVE_STRINGS_H", DAO_DOUBLE, HAVE_STRINGS_H},
  {  "HAVE_STRING_H", DAO_DOUBLE, HAVE_STRING_H},
  {  "HAVE_STRLCAT", DAO_DOUBLE, HAVE_STRLCAT},
  {  "HAVE_STRLCPY", DAO_DOUBLE, HAVE_STRLCPY},
  {  "HAVE_STRLEN", DAO_DOUBLE, HAVE_STRLEN},
  {  "HAVE_STRNCASECMP", DAO_DOUBLE, HAVE_STRNCASECMP},
  {  "HAVE_STRNCMP", DAO_DOUBLE, HAVE_STRNCMP},
  {  "HAVE_STRRCHR", DAO_DOUBLE, HAVE_STRRCHR},
  {  "HAVE_STRSTR", DAO_DOUBLE, HAVE_STRSTR},
  {  "HAVE_STRTOD", DAO_DOUBLE, HAVE_STRTOD},
  {  "HAVE_STRTOL", DAO_DOUBLE, HAVE_STRTOL},
  {  "HAVE_STRTOLL", DAO_DOUBLE, HAVE_STRTOLL},
  {  "HAVE_STRTOUL", DAO_DOUBLE, HAVE_STRTOUL},
  {  "HAVE_STRTOULL", DAO_DOUBLE, HAVE_STRTOULL},
  {  "HAVE_SYSCONF", DAO_DOUBLE, HAVE_SYSCONF},
  {  "HAVE_SYSCTLBYNAME", DAO_DOUBLE, HAVE_SYSCTLBYNAME},
  {  "HAVE_SYS_TYPES_H", DAO_DOUBLE, HAVE_SYS_TYPES_H},
  {  "HAVE_UNSETENV", DAO_DOUBLE, HAVE_UNSETENV},
  {  "HAVE_VSNPRINTF", DAO_DOUBLE, HAVE_VSNPRINTF},
  {  "ICONV_GET_DISCARD_ILSEQ", DAO_DOUBLE, ICONV_GET_DISCARD_ILSEQ},
  {  "ICONV_GET_TRANSLITERATE", DAO_DOUBLE, ICONV_GET_TRANSLITERATE},
  {  "ICONV_SET_DISCARD_ILSEQ", DAO_DOUBLE, ICONV_SET_DISCARD_ILSEQ},
  {  "ICONV_SET_FALLBACKS", DAO_DOUBLE, ICONV_SET_FALLBACKS},
  {  "ICONV_SET_HOOKS", DAO_DOUBLE, ICONV_SET_HOOKS},
  {  "ICONV_SET_TRANSLITERATE", DAO_DOUBLE, ICONV_SET_TRANSLITERATE},
  {  "ICONV_TRIVIALP", DAO_DOUBLE, ICONV_TRIVIALP},
  {  "ILL_BADSTK", DAO_DOUBLE, ILL_BADSTK},
  {  "ILL_COPROC", DAO_DOUBLE, ILL_COPROC},
  {  "ILL_ILLADR", DAO_DOUBLE, ILL_ILLADR},
  {  "ILL_ILLOPC", DAO_DOUBLE, ILL_ILLOPC},
  {  "ILL_ILLOPN", DAO_DOUBLE, ILL_ILLOPN},
  {  "ILL_ILLTRP", DAO_DOUBLE, ILL_ILLTRP},
  {  "ILL_NOOP", DAO_DOUBLE, ILL_NOOP},
  {  "ILL_PRVOPC", DAO_DOUBLE, ILL_PRVOPC},
  {  "ILL_PRVREG", DAO_DOUBLE, ILL_PRVREG},
  {  "INT16_MAX", DAO_DOUBLE, INT16_MAX},
  {  "INT32_MAX", DAO_DOUBLE, INT32_MAX},
  {  "INT64_MAX", DAO_DOUBLE, INT64_MAX},
  {  "INT8_MAX", DAO_DOUBLE, INT8_MAX},
  {  "IOPOL_DEFAULT", DAO_DOUBLE, IOPOL_DEFAULT},
  {  "IOPOL_NORMAL", DAO_DOUBLE, IOPOL_NORMAL},
  {  "IOPOL_PASSIVE", DAO_DOUBLE, IOPOL_PASSIVE},
  {  "IOPOL_SCOPE_PROCESS", DAO_DOUBLE, IOPOL_SCOPE_PROCESS},
  {  "IOPOL_SCOPE_THREAD", DAO_DOUBLE, IOPOL_SCOPE_THREAD},
  {  "IOPOL_THROTTLE", DAO_DOUBLE, IOPOL_THROTTLE},
  {  "IOPOL_TYPE_DISK", DAO_DOUBLE, IOPOL_TYPE_DISK},
  {  "L_ctermid", DAO_DOUBLE, L_ctermid},
  {  "L_tmpnam", DAO_DOUBLE, L_tmpnam},
  {  "MAC_OS_X_VERSION_10_0", DAO_DOUBLE, MAC_OS_X_VERSION_10_0},
  {  "MAC_OS_X_VERSION_10_1", DAO_DOUBLE, MAC_OS_X_VERSION_10_1},
  {  "MAC_OS_X_VERSION_10_2", DAO_DOUBLE, MAC_OS_X_VERSION_10_2},
  {  "MAC_OS_X_VERSION_10_3", DAO_DOUBLE, MAC_OS_X_VERSION_10_3},
  {  "MAC_OS_X_VERSION_10_4", DAO_DOUBLE, MAC_OS_X_VERSION_10_4},
  {  "MAC_OS_X_VERSION_10_5", DAO_DOUBLE, MAC_OS_X_VERSION_10_5},
  {  "MATH_ERREXCEPT", DAO_DOUBLE, MATH_ERREXCEPT},
  {  "MATH_ERRNO", DAO_DOUBLE, MATH_ERRNO},
  {  "MINSIGSTKSZ", DAO_DOUBLE, MINSIGSTKSZ},
  {  "M_1_PI", DAO_DOUBLE, M_1_PI},
  {  "M_2_PI", DAO_DOUBLE, M_2_PI},
  {  "M_2_SQRTPI", DAO_DOUBLE, M_2_SQRTPI},
  {  "M_E", DAO_DOUBLE, M_E},
  {  "M_LN10", DAO_DOUBLE, M_LN10},
  {  "M_LN2", DAO_DOUBLE, M_LN2},
  {  "M_LOG10E", DAO_DOUBLE, M_LOG10E},
  {  "M_LOG2E", DAO_DOUBLE, M_LOG2E},
  {  "M_PI", DAO_DOUBLE, M_PI},
  {  "M_PI_2", DAO_DOUBLE, M_PI_2},
  {  "M_PI_4", DAO_DOUBLE, M_PI_4},
  {  "M_SQRT1_2", DAO_DOUBLE, M_SQRT1_2},
  {  "M_SQRT2", DAO_DOUBLE, M_SQRT2},
  {  "OBJC_NEW_PROPERTIES", DAO_DOUBLE, OBJC_NEW_PROPERTIES},
  {  "OS_SPINLOCK_INIT", DAO_DOUBLE, OS_SPINLOCK_INIT},
  {  "OVERFLOW", DAO_DOUBLE, OVERFLOW},
  {  "PLOSS", DAO_DOUBLE, PLOSS},
  {  "POLL_ERR", DAO_DOUBLE, POLL_ERR},
  {  "POLL_HUP", DAO_DOUBLE, POLL_HUP},
  {  "POLL_IN", DAO_DOUBLE, POLL_IN},
  {  "POLL_MSG", DAO_DOUBLE, POLL_MSG},
  {  "POLL_OUT", DAO_DOUBLE, POLL_OUT},
  {  "POLL_PRI", DAO_DOUBLE, POLL_PRI},
  {  "PRIO_DARWIN_BG", DAO_DOUBLE, PRIO_DARWIN_BG},
  {  "PRIO_DARWIN_THREAD", DAO_DOUBLE, PRIO_DARWIN_THREAD},
  {  "PRIO_MAX", DAO_DOUBLE, PRIO_MAX},
  {  "PRIO_PGRP", DAO_DOUBLE, PRIO_PGRP},
  {  "PRIO_PROCESS", DAO_DOUBLE, PRIO_PROCESS},
  {  "PRIO_USER", DAO_DOUBLE, PRIO_USER},
  {  "RAND_MAX", DAO_DOUBLE, RAND_MAX},
  {  "RLIMIT_AS", DAO_DOUBLE, RLIMIT_AS},
  {  "RLIMIT_CORE", DAO_DOUBLE, RLIMIT_CORE},
  {  "RLIMIT_CPU", DAO_DOUBLE, RLIMIT_CPU},
  {  "RLIMIT_DATA", DAO_DOUBLE, RLIMIT_DATA},
  {  "RLIMIT_FSIZE", DAO_DOUBLE, RLIMIT_FSIZE},
  {  "RLIMIT_MEMLOCK", DAO_DOUBLE, RLIMIT_MEMLOCK},
  {  "RLIMIT_NOFILE", DAO_DOUBLE, RLIMIT_NOFILE},
  {  "RLIMIT_NPROC", DAO_DOUBLE, RLIMIT_NPROC},
  {  "RLIMIT_STACK", DAO_DOUBLE, RLIMIT_STACK},
  {  "RLIM_NLIMITS", DAO_DOUBLE, RLIM_NLIMITS},
  {  "RUSAGE_SELF", DAO_DOUBLE, RUSAGE_SELF},
  {  "RW_SEEK_CUR", DAO_DOUBLE, RW_SEEK_CUR},
  {  "RW_SEEK_END", DAO_DOUBLE, RW_SEEK_END},
  {  "RW_SEEK_SET", DAO_DOUBLE, RW_SEEK_SET},
  {  "SA_64REGSET", DAO_DOUBLE, SA_64REGSET},
  {  "SA_NOCLDSTOP", DAO_DOUBLE, SA_NOCLDSTOP},
  {  "SA_NOCLDWAIT", DAO_DOUBLE, SA_NOCLDWAIT},
  {  "SA_NODEFER", DAO_DOUBLE, SA_NODEFER},
  {  "SA_ONSTACK", DAO_DOUBLE, SA_ONSTACK},
  {  "SA_RESETHAND", DAO_DOUBLE, SA_RESETHAND},
  {  "SA_RESTART", DAO_DOUBLE, SA_RESTART},
  {  "SA_SIGINFO", DAO_DOUBLE, SA_SIGINFO},
  {  "SA_USERTRAMP", DAO_DOUBLE, SA_USERTRAMP},
  {  "SDL_ALPHA_OPAQUE", DAO_DOUBLE, SDL_ALPHA_OPAQUE},
  {  "SDL_ALPHA_TRANSPARENT", DAO_DOUBLE, SDL_ALPHA_TRANSPARENT},
  {  "SDL_ASSEMBLY_ROUTINES", DAO_DOUBLE, SDL_ASSEMBLY_ROUTINES},
  {  "SDL_ASSERT_LEVEL", DAO_DOUBLE, SDL_ASSERT_LEVEL},
  {  "SDL_AUDIO_ALLOW_CHANNELS_CHANGE", DAO_DOUBLE, SDL_AUDIO_ALLOW_CHANNELS_CHANGE},
  {  "SDL_AUDIO_ALLOW_FORMAT_CHANGE", DAO_DOUBLE, SDL_AUDIO_ALLOW_FORMAT_CHANGE},
  {  "SDL_AUDIO_ALLOW_FREQUENCY_CHANGE", DAO_DOUBLE, SDL_AUDIO_ALLOW_FREQUENCY_CHANGE},
  {  "SDL_AUDIO_DRIVER_COREAUDIO", DAO_DOUBLE, SDL_AUDIO_DRIVER_COREAUDIO},
  {  "SDL_AUDIO_DRIVER_DISK", DAO_DOUBLE, SDL_AUDIO_DRIVER_DISK},
  {  "SDL_AUDIO_DRIVER_DUMMY", DAO_DOUBLE, SDL_AUDIO_DRIVER_DUMMY},
  {  "SDL_BIG_ENDIAN", DAO_DOUBLE, SDL_BIG_ENDIAN},
  {  "SDL_BUTTON_LEFT", DAO_DOUBLE, SDL_BUTTON_LEFT},
  {  "SDL_BUTTON_MIDDLE", DAO_DOUBLE, SDL_BUTTON_MIDDLE},
  {  "SDL_BUTTON_RIGHT", DAO_DOUBLE, SDL_BUTTON_RIGHT},
  {  "SDL_BUTTON_X1", DAO_DOUBLE, SDL_BUTTON_X1},
  {  "SDL_BUTTON_X2", DAO_DOUBLE, SDL_BUTTON_X2},
  {  "SDL_CACHELINE_SIZE", DAO_DOUBLE, SDL_CACHELINE_SIZE},
  {  "SDL_DISABLE", DAO_DOUBLE, SDL_DISABLE},
  {  "SDL_DONTFREE", DAO_DOUBLE, SDL_DONTFREE},
  {  "SDL_ENABLE", DAO_DOUBLE, SDL_ENABLE},
  {  "SDL_HAPTIC_IOKIT", DAO_DOUBLE, SDL_HAPTIC_IOKIT},
  {  "SDL_HAT_CENTERED", DAO_DOUBLE, SDL_HAT_CENTERED},
  {  "SDL_HAT_DOWN", DAO_DOUBLE, SDL_HAT_DOWN},
  {  "SDL_HAT_LEFT", DAO_DOUBLE, SDL_HAT_LEFT},
  {  "SDL_HAT_RIGHT", DAO_DOUBLE, SDL_HAT_RIGHT},
  {  "SDL_HAT_UP", DAO_DOUBLE, SDL_HAT_UP},
  {  "SDL_IGNORE", DAO_DOUBLE, SDL_IGNORE},
  {  "SDL_INIT_AUDIO", DAO_DOUBLE, SDL_INIT_AUDIO},
  {  "SDL_INIT_EVERYTHING", DAO_DOUBLE, SDL_INIT_EVERYTHING},
  {  "SDL_INIT_HAPTIC", DAO_DOUBLE, SDL_INIT_HAPTIC},
  {  "SDL_INIT_JOYSTICK", DAO_DOUBLE, SDL_INIT_JOYSTICK},
  {  "SDL_INIT_NOPARACHUTE", DAO_DOUBLE, SDL_INIT_NOPARACHUTE},
  {  "SDL_INIT_TIMER", DAO_DOUBLE, SDL_INIT_TIMER},
  {  "SDL_INIT_VIDEO", DAO_DOUBLE, SDL_INIT_VIDEO},
  {  "SDL_JOYSTICK_IOKIT", DAO_DOUBLE, SDL_JOYSTICK_IOKIT},
  {  "SDL_LIL_ENDIAN", DAO_DOUBLE, SDL_LIL_ENDIAN},
  {  "SDL_LOADSO_DLOPEN", DAO_DOUBLE, SDL_LOADSO_DLOPEN},
  {  "SDL_MAJOR_VERSION", DAO_DOUBLE, SDL_MAJOR_VERSION},
  {  "SDL_MAX_LOG_MESSAGE", DAO_DOUBLE, SDL_MAX_LOG_MESSAGE},
  {  "SDL_MINOR_VERSION", DAO_DOUBLE, SDL_MINOR_VERSION},
  {  "SDL_MIX_MAXVOLUME", DAO_DOUBLE, SDL_MIX_MAXVOLUME},
  {  "SDL_MUTEX_TIMEDOUT", DAO_DOUBLE, SDL_MUTEX_TIMEDOUT},
  {  "SDL_PATCHLEVEL", DAO_DOUBLE, SDL_PATCHLEVEL},
  {  "SDL_POWER_MACOSX", DAO_DOUBLE, SDL_POWER_MACOSX},
  {  "SDL_PREALLOC", DAO_DOUBLE, SDL_PREALLOC},
  {  "SDL_PRESSED", DAO_DOUBLE, SDL_PRESSED},
  {  "SDL_RELEASED", DAO_DOUBLE, SDL_RELEASED},
  {  "SDL_RLEACCEL", DAO_DOUBLE, SDL_RLEACCEL},
  {  "SDL_SWSURFACE", DAO_DOUBLE, SDL_SWSURFACE},
  {  "SDL_THREAD_PTHREAD", DAO_DOUBLE, SDL_THREAD_PTHREAD},
  {  "SDL_THREAD_PTHREAD_RECURSIVE_MUTEX", DAO_DOUBLE, SDL_THREAD_PTHREAD_RECURSIVE_MUTEX},
  {  "SDL_TIMER_UNIX", DAO_DOUBLE, SDL_TIMER_UNIX},
  {  "SDL_VIDEO_DRIVER_COCOA", DAO_DOUBLE, SDL_VIDEO_DRIVER_COCOA},
  {  "SDL_VIDEO_DRIVER_DUMMY", DAO_DOUBLE, SDL_VIDEO_DRIVER_DUMMY},
  {  "SDL_VIDEO_DRIVER_X11", DAO_DOUBLE, SDL_VIDEO_DRIVER_X11},
  {  "SDL_VIDEO_DRIVER_X11_XCURSOR", DAO_DOUBLE, SDL_VIDEO_DRIVER_X11_XCURSOR},
  {  "SDL_VIDEO_DRIVER_X11_XINERAMA", DAO_DOUBLE, SDL_VIDEO_DRIVER_X11_XINERAMA},
  {  "SDL_VIDEO_DRIVER_X11_XINPUT", DAO_DOUBLE, SDL_VIDEO_DRIVER_X11_XINPUT},
  {  "SDL_VIDEO_DRIVER_X11_XRANDR", DAO_DOUBLE, SDL_VIDEO_DRIVER_X11_XRANDR},
  {  "SDL_VIDEO_DRIVER_X11_XSCRNSAVER", DAO_DOUBLE, SDL_VIDEO_DRIVER_X11_XSCRNSAVER},
  {  "SDL_VIDEO_DRIVER_X11_XSHAPE", DAO_DOUBLE, SDL_VIDEO_DRIVER_X11_XSHAPE},
  {  "SDL_VIDEO_DRIVER_X11_XVIDMODE", DAO_DOUBLE, SDL_VIDEO_DRIVER_X11_XVIDMODE},
  {  "SDL_VIDEO_OPENGL", DAO_DOUBLE, SDL_VIDEO_OPENGL},
  {  "SDL_VIDEO_OPENGL_CGL", DAO_DOUBLE, SDL_VIDEO_OPENGL_CGL},
  {  "SDL_VIDEO_OPENGL_GLX", DAO_DOUBLE, SDL_VIDEO_OPENGL_GLX},
  {  "SDL_VIDEO_RENDER_OGL", DAO_DOUBLE, SDL_VIDEO_RENDER_OGL},
  {  "SDL_WINDOWPOS_CENTERED_MASK", DAO_DOUBLE, SDL_WINDOWPOS_CENTERED_MASK},
  {  "SDL_WINDOWPOS_UNDEFINED_MASK", DAO_DOUBLE, SDL_WINDOWPOS_UNDEFINED_MASK},
  {  "SEEK_CUR", DAO_DOUBLE, SEEK_CUR},
  {  "SEEK_END", DAO_DOUBLE, SEEK_END},
  {  "SEEK_SET", DAO_DOUBLE, SEEK_SET},
  {  "SEGV_ACCERR", DAO_DOUBLE, SEGV_ACCERR},
  {  "SEGV_MAPERR", DAO_DOUBLE, SEGV_MAPERR},
  {  "SEGV_NOOP", DAO_DOUBLE, SEGV_NOOP},
  {  "SIGABRT", DAO_DOUBLE, SIGABRT},
  {  "SIGALRM", DAO_DOUBLE, SIGALRM},
  {  "SIGBUS", DAO_DOUBLE, SIGBUS},
  {  "SIGCHLD", DAO_DOUBLE, SIGCHLD},
  {  "SIGCONT", DAO_DOUBLE, SIGCONT},
  {  "SIGEMT", DAO_DOUBLE, SIGEMT},
  {  "SIGEV_NONE", DAO_DOUBLE, SIGEV_NONE},
  {  "SIGEV_SIGNAL", DAO_DOUBLE, SIGEV_SIGNAL},
  {  "SIGEV_THREAD", DAO_DOUBLE, SIGEV_THREAD},
  {  "SIGFPE", DAO_DOUBLE, SIGFPE},
  {  "SIGHUP", DAO_DOUBLE, SIGHUP},
  {  "SIGILL", DAO_DOUBLE, SIGILL},
  {  "SIGINFO", DAO_DOUBLE, SIGINFO},
  {  "SIGINT", DAO_DOUBLE, SIGINT},
  {  "SIGIO", DAO_DOUBLE, SIGIO},
  {  "SIGKILL", DAO_DOUBLE, SIGKILL},
  {  "SIGPIPE", DAO_DOUBLE, SIGPIPE},
  {  "SIGPROF", DAO_DOUBLE, SIGPROF},
  {  "SIGQUIT", DAO_DOUBLE, SIGQUIT},
  {  "SIGSEGV", DAO_DOUBLE, SIGSEGV},
  {  "SIGSTKSZ", DAO_DOUBLE, SIGSTKSZ},
  {  "SIGSTOP", DAO_DOUBLE, SIGSTOP},
  {  "SIGSYS", DAO_DOUBLE, SIGSYS},
  {  "SIGTERM", DAO_DOUBLE, SIGTERM},
  {  "SIGTRAP", DAO_DOUBLE, SIGTRAP},
  {  "SIGTSTP", DAO_DOUBLE, SIGTSTP},
  {  "SIGTTIN", DAO_DOUBLE, SIGTTIN},
  {  "SIGTTOU", DAO_DOUBLE, SIGTTOU},
  {  "SIGURG", DAO_DOUBLE, SIGURG},
  {  "SIGUSR1", DAO_DOUBLE, SIGUSR1},
  {  "SIGUSR2", DAO_DOUBLE, SIGUSR2},
  {  "SIGVTALRM", DAO_DOUBLE, SIGVTALRM},
  {  "SIGWINCH", DAO_DOUBLE, SIGWINCH},
  {  "SIGXCPU", DAO_DOUBLE, SIGXCPU},
  {  "SIGXFSZ", DAO_DOUBLE, SIGXFSZ},
  {  "SIG_BLOCK", DAO_DOUBLE, SIG_BLOCK},
  {  "SIG_SETMASK", DAO_DOUBLE, SIG_SETMASK},
  {  "SIG_UNBLOCK", DAO_DOUBLE, SIG_UNBLOCK},
  {  "SING", DAO_DOUBLE, SING},
  {  "SIZEOF_VOIDP", DAO_DOUBLE, SIZEOF_VOIDP},
  {  "SI_ASYNCIO", DAO_DOUBLE, SI_ASYNCIO},
  {  "SI_MESGQ", DAO_DOUBLE, SI_MESGQ},
  {  "SI_QUEUE", DAO_DOUBLE, SI_QUEUE},
  {  "SI_TIMER", DAO_DOUBLE, SI_TIMER},
  {  "SI_USER", DAO_DOUBLE, SI_USER},
  {  "SS_DISABLE", DAO_DOUBLE, SS_DISABLE},
  {  "SS_ONSTACK", DAO_DOUBLE, SS_ONSTACK},
  {  "STDC_HEADERS", DAO_DOUBLE, STDC_HEADERS},
  {  "TARGET_CPU_68K", DAO_DOUBLE, TARGET_CPU_68K},
  {  "TARGET_CPU_ALPHA", DAO_DOUBLE, TARGET_CPU_ALPHA},
  {  "TARGET_CPU_MIPS", DAO_DOUBLE, TARGET_CPU_MIPS},
  {  "TARGET_CPU_PPC", DAO_DOUBLE, TARGET_CPU_PPC},
  {  "TARGET_CPU_PPC64", DAO_DOUBLE, TARGET_CPU_PPC64},
  {  "TARGET_CPU_SPARC", DAO_DOUBLE, TARGET_CPU_SPARC},
  {  "TARGET_CPU_X86", DAO_DOUBLE, TARGET_CPU_X86},
  {  "TARGET_CPU_X86_64", DAO_DOUBLE, TARGET_CPU_X86_64},
  {  "TARGET_OS_EMBEDDED", DAO_DOUBLE, TARGET_OS_EMBEDDED},
  {  "TARGET_OS_MAC", DAO_DOUBLE, TARGET_OS_MAC},
  {  "TARGET_OS_UNIX", DAO_DOUBLE, TARGET_OS_UNIX},
  {  "TARGET_OS_WIN32", DAO_DOUBLE, TARGET_OS_WIN32},
  {  "TARGET_RT_64_BIT", DAO_DOUBLE, TARGET_RT_64_BIT},
  {  "TARGET_RT_BIG_ENDIAN", DAO_DOUBLE, TARGET_RT_BIG_ENDIAN},
  {  "TARGET_RT_LITTLE_ENDIAN", DAO_DOUBLE, TARGET_RT_LITTLE_ENDIAN},
  {  "TARGET_RT_MAC_CFM", DAO_DOUBLE, TARGET_RT_MAC_CFM},
  {  "TARGET_RT_MAC_MACHO", DAO_DOUBLE, TARGET_RT_MAC_MACHO},
  {  "TLOSS", DAO_DOUBLE, TLOSS},
  {  "TMP_MAX", DAO_DOUBLE, TMP_MAX},
  {  "TRAP_BRKPT", DAO_DOUBLE, TRAP_BRKPT},
  {  "TRAP_TRACE", DAO_DOUBLE, TRAP_TRACE},
  {  "UINT16_MAX", DAO_DOUBLE, UINT16_MAX},
  {  "UINT32_MAX", DAO_DOUBLE, UINT32_MAX},
  {  "UINT64_MAX", DAO_DOUBLE, UINT64_MAX},
  {  "UINT8_MAX", DAO_DOUBLE, UINT8_MAX},
  {  "UNDERFLOW", DAO_DOUBLE, UNDERFLOW},
  {  "VERBOSE_AUDIO", DAO_DOUBLE, VERBOSE_AUDIO},
  {  "VERBOSE_EVENT", DAO_DOUBLE, VERBOSE_EVENT},
  {  "VERBOSE_MODES", DAO_DOUBLE, VERBOSE_MODES},
  {  "VERBOSE_RENDER", DAO_DOUBLE, VERBOSE_RENDER},
  {  "VERBOSE_VIDEO", DAO_DOUBLE, VERBOSE_VIDEO},
  {  "WAIT_MYPGRP", DAO_DOUBLE, WAIT_MYPGRP},
  {  "WCONTINUED", DAO_DOUBLE, WCONTINUED},
  {  "WCOREFLAG", DAO_DOUBLE, WCOREFLAG},
  {  "WEXITED", DAO_DOUBLE, WEXITED},
  {  "WNOHANG", DAO_DOUBLE, WNOHANG},
  {  "WNOWAIT", DAO_DOUBLE, WNOWAIT},
  {  "WSTOPPED", DAO_DOUBLE, WSTOPPED},
  {  "WUNTRACED", DAO_DOUBLE, WUNTRACED},
  {  "X_TLOSS", DAO_DOUBLE, X_TLOSS},
  {  "false", DAO_DOUBLE, false},
  {  "i386", DAO_DOUBLE, i386},
  {  "true", DAO_DOUBLE, true},
  { NULL, 0, 0 }
};
static const char *dao__Aliases[] = 
{
	NULL
};
#ifdef __cplusplus
extern "C"{
#endif
int DaoOnLoad( DaoVmSpace *vms, DaoNamespace *ns )
{
	__daoVmSpace = vms;
	DaoNamespace *SDL = DaoVmSpace_LinkModule( vms, ns, "SDL" );
	if( SDL == NULL ) SDL = DaoVmSpace_LinkModule( vms, ns, "DaoSDL" );
	if( SDL == NULL ) return 1;
	DaoNamespace_AddConstNumbers( ns, dao__Nums );
	dao_type_CommonState = DaoNamespace_WrapType( ns, dao_CommonState_Typer, 1 );
	DaoNamespace_TypeDefines( ns, dao__Aliases );
	DaoNamespace_WrapFunctions( ns, dao__Funcs );
	return 0;
}
#ifdef __cplusplus
}
#endif
